# Obsidian Agent Configuration Example
# Kopiere diese Datei zu config.yaml und passe sie an deine Bedürfnisse an

# Obsidian Vault Settings
vault:
  path: "/Users/deinname/Documents/MeinObsidianVault"  # WICHTIG: Passe diesen Pfad an!
  
# LLM Provider Settings - wähle einen Provider aus
llm:
  provider: "ollama"  # Options: "ollama", "openai", "claude"
  
  # Ollama Settings (Standard - funktioniert lokal)
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.1"  # oder llama2, codellama, etc.
    
  # OpenAI Settings (benötigt API-Key)
  openai:
    api_key: "sk-your-openai-api-key-here"  # Dein OpenAI API Key
    model: "gpt-3.5-turbo"  # oder gpt-4
    max_tokens: 2000
    
  # Claude Settings (benötigt API-Key)
  claude:
    api_key: "your-claude-api-key-here"  # Dein Anthropic API Key
    model: "claude-3-sonnet-20240229"  # oder claude-3-haiku-20240307
    max_tokens: 2000

# Agent Behavior Settings
agent:
  max_notes_per_query: 10      # Maximum Anzahl Notizen pro Anfrage
  search_depth: "content"      # Options: "title", "content", "both" 
  summary_max_length: 500      # Maximale Länge von Zusammenfassungen